In [ ]:
print ('Hi')

Hi


In [ ]:
#a
import numpy as np


In [ ]:
#b
a = np.array ([0,0,0,0,0,0,0,0,0,0], int)
print (a)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#c
a= np.array ([1,1,1,1,1,1,1,1,1,1], int)
print (a)

[1 1 1 1 1 1 1 1 1 1]


In [ ]:
#d
a= np.array ([5,5,5,5,5,5,5,5,5,5], int)
print (a)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#e
a= np.arange(10,50)
print (a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#f
a= np.arange(10,50,2)
print (a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
#g
a = np.array([[0,1,2], 
    [3,4,5],
    [6,7,8]])
print (a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#h
a= np.identity (3)
print (a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#i
import random
print (random.randrange(0,1))

0


In [ ]:
#j
a= np.random.randn(25)
print (a)

[ 0.36583174 -0.02311187  0.37864668  0.09848989  0.48643242  0.76616723
 -1.21444962 -0.43769896 -0.36031631 -0.79143829 -0.82680475 -0.65274915
  1.20010541 -0.80945029  0.40135033  0.29431878  0.20375696 -0.21841406
 -0.57091877  0.82277296 -0.87439977 -1.22267805 -0.16736483 -1.18479271
 -1.80101677]


In [ ]:
#k
a = np.arange(0.01, 1, 0.01)

print (a)

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99]


In [ ]:
a = np.array ([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1],
               [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2],
               [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3],
               [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4],
               [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.4, 0.49, 0.5],
               [0.51, 0.52, 0.53, 0.5, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6],
               [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7],
               [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
               [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9],
               [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,1]])
print (a)
# код корявенький, но я не знаю как сделать проще))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.4  0.49 0.5 ]
 [0.51 0.52 0.53 0.5  0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
#l
mat = np.arange(1,26).reshape(5,5)
print (mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:

mat = np.arange(1,26).reshape(5,5)
print(mat [2,1:5])
print(mat [3,1:5])
print(mat [4,1:5])

[12 13 14 15]
[17 18 19 20]
[22 23 24 25]


In [ ]:
#m
mat = np.arange(1,26).reshape(5,5)
print(mat [3,4])

20


In [ ]:
#n
mat = np.arange(1,26).reshape(5,5)
a = mat [0,1]
b = mat [1,1]
c = mat[2,1]
print ([a])
print ([b])
print ([c])

[2]
[7]
[12]


In [ ]:
#o
mat = np.arange(1,26).reshape(5,5)
print (mat [4,0:5])

[21 22 23 24 25]


In [ ]:
#p
mat = np.arange(1,26).reshape(5,5)
print (mat [3,0:5])
print (mat [4,0:5])

[16 17 18 19 20]
[21 22 23 24 25]


In [ ]:
#q
mat = np.arange(1,26).reshape(5,5)
print (mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
A = np.sum(mat)
print (A)

325


In [ ]:
#r
mat = np.arange(1,26).reshape(5,5)
A = np.std(mat)
print (A)

7.211102550927978


In [ ]:
#s
mat = np.arange(1,26).reshape(5,5)
A = np.sum (mat, axis = 0)
print (A)

[55 60 65 70 75]
